// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package org.zoominfo.drive;

public interface DownloadFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:file_service.DownloadFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
