// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package org.zoominfo.drive;

public final class FileServiceProto {
  private FileServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_file_service_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_file_service_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_file_service_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_file_service_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022file_service.proto\022\014file_service\"2\n\014Lo" +
      "ginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010password" +
      "\030\002 \001(\t\"@\n\rLoginResponse\022\r\n\005token\030\001 \001(\t\022\017" +
      "\n\007success\030\002 \001(\010\022\017\n\007message\030\003 \001(\t2O\n\013File" +
      "Service\022@\n\005login\022\032.file_service.LoginReq" +
      "uest\032\033.file_service.LoginResponseB(\n\022org" +
      ".zoominfo.driveB\020FileServiceProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_file_service_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_file_service_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_file_service_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_file_service_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_file_service_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_file_service_LoginResponse_descriptor,
        new java.lang.String[] { "Token", "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
