// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package org.zoominfo.drive;

public interface SignupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:file_service.SignupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
